version: "3.8"

services:
  backend:
    image: backend:v2.0.1
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=*
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    container_name: backend

  frontend:
    image: frontend:v2.0.1
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    container_name: frontend

  cache:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - store:/data

  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data

  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  store:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./store
