version: "3.8"

services:
  web:
    image: akhonya/express-app:latest
    container_name: web
    ports:
      - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  watcher:
    image: containrrr/watchtower
    container_name: watcher
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LOG_LEVEL=info
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_LABEL_ENABLE=true
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
